package ui.gui.panels;

import javax.swing.JPanel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import javax.swing.JSeparator;
import java.awt.Insets;
import javax.swing.JScrollPane;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.BevelBorder;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.border.EmptyBorder;

public class Mitarbeiter_Menue extends JPanel {
	private final JPanel panel = new JPanel();
	private final JPanel panel_hallo = new JPanel();
	private final JSeparator separator = new JSeparator();
	private final JPanel panel_mitarbeiterMenue = new JPanel();
	private final JPanel panel_1 = new JPanel();
	private final JScrollPane scrollPane = new JScrollPane();
	private final JPanel panel_2_1 = new JPanel();
	private final JPanel panel_12_1 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_1 = new JPanel();
	private final JPanel panel_12_1_1 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_1 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_2 = new JPanel();
	private final JPanel panel_12_1_2 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_2 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_3 = new JPanel();
	private final JPanel panel_12_1_3 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_3 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_4 = new JPanel();
	private final JPanel panel_12_1_4 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_4 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_5 = new JPanel();
	private final JPanel panel_12_1_5 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_5 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_6 = new JPanel();
	private final JPanel panel_12_1_6 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_6 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_7 = new JPanel();
	private final JPanel panel_12_1_7 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_7 = new JLabel("Artikeln anzeigen");
	private final JPanel panel_2_1_8 = new JPanel();
	private final JPanel panel_12_1_8 = new JPanel();
	private final JLabel lbl_ArtikelnAnzeigen_1_8 = new JLabel("Artikeln anzeigen");
	private final JLabel lblNewLabel = new JLabel("Hallo Joe");

	/**
	 * Create the panel.
	 */
	public Mitarbeiter_Menue() {

		initGUI();
	}
	private void initGUI() {
		setForeground(Color.DARK_GRAY);
		setBackground(Color.DARK_GRAY);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{120, 0};
		gridBagLayout.rowHeights = new int[]{62, 0};
		gridBagLayout.columnWeights = new double[]{1.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		setLayout(gridBagLayout);
		
		GridBagConstraints gbc_panel = new GridBagConstraints();
		gbc_panel.ipady = 10;
		gbc_panel.fill = GridBagConstraints.BOTH;
		gbc_panel.gridx = 0;
		gbc_panel.gridy = 0;
		panel.setBackground(Color.DARK_GRAY);
		add(panel, gbc_panel);
		panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
		FlowLayout flowLayout = (FlowLayout) panel_hallo.getLayout();
		flowLayout.setAlignment(FlowLayout.LEFT);
		panel_hallo.setBorder(new EmptyBorder(0, 0, 10, 0));
		panel_hallo.setBackground(Color.DARK_GRAY);
		panel.add(panel_hallo);
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel.setForeground(Color.ORANGE);
		
		panel_hallo.add(lblNewLabel);
		separator.setForeground(Color.DARK_GRAY);
		separator.setBackground(Color.ORANGE);
		panel.add(separator);
		panel_mitarbeiterMenue.setForeground(Color.DARK_GRAY);
		panel_mitarbeiterMenue.setBorder(new EmptyBorder(10, 0, 0, 0));
		panel_mitarbeiterMenue.setBackground(Color.DARK_GRAY);
		panel.add(panel_mitarbeiterMenue);
		GridBagLayout gbl_panel_mitarbeiterMenue = new GridBagLayout();
		gbl_panel_mitarbeiterMenue.columnWidths = new int[]{135, 0};
		gbl_panel_mitarbeiterMenue.rowHeights = new int[]{12, 0};
		gbl_panel_mitarbeiterMenue.columnWeights = new double[]{1.0, Double.MIN_VALUE};
		gbl_panel_mitarbeiterMenue.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_mitarbeiterMenue.setLayout(gbl_panel_mitarbeiterMenue);
		
		GridBagConstraints gbc_scrollPane = new GridBagConstraints();
		gbc_scrollPane.fill = GridBagConstraints.BOTH;
		gbc_scrollPane.gridx = 0;
		gbc_scrollPane.gridy = 0;
		panel_mitarbeiterMenue.add(scrollPane, gbc_scrollPane);
		panel_1.setForeground(Color.DARK_GRAY);
		panel_1.setBackground(Color.DARK_GRAY);
		scrollPane.setViewportView(panel_1);
		GridBagLayout gbl_panel_1 = new GridBagLayout();
		gbl_panel_1.columnWidths = new int[]{149, 0};
		gbl_panel_1.rowHeights = new int[]{20, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		gbl_panel_1.columnWeights = new double[]{1.0, Double.MIN_VALUE};
		gbl_panel_1.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_1.setLayout(gbl_panel_1);
		panel_2_1.setBackground(Color.DARK_GRAY);
		
		GridBagConstraints gbc_panel_2_1 = new GridBagConstraints();
		gbc_panel_2_1.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1.fill = GridBagConstraints.HORIZONTAL;
		gbc_panel_2_1.gridx = 0;
		gbc_panel_2_1.gridy = 0;
		panel_1.add(panel_2_1, gbc_panel_2_1);
		GridBagLayout gbl_panel_2_1 = new GridBagLayout();
		gbl_panel_2_1.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1.rowHeights = new int[]{13, 0};
		gbl_panel_2_1.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1.setLayout(gbl_panel_2_1);
		
		GridBagConstraints gbc_panel_12_1 = new GridBagConstraints();
		gbc_panel_12_1.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1.gridx = 0;
		gbc_panel_12_1.gridy = 0;
		panel_12_1.setForeground(Color.ORANGE);
		panel_12_1.setBorder(null);
		panel_12_1.setBackground(Color.ORANGE);
		panel_2_1.add(panel_12_1, gbc_panel_12_1);
		GridBagLayout gbl_panel_12_1 = new GridBagLayout();
		gbl_panel_12_1.columnWidths = new int[]{0};
		gbl_panel_12_1.rowHeights = new int[]{0};
		gbl_panel_12_1.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1.setLayout(gbl_panel_12_1);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1.gridy = 0;
		lbl_ArtikelnAnzeigen_1.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1.add(lbl_ArtikelnAnzeigen_1, gbc_lbl_ArtikelnAnzeigen_1);
		
		GridBagConstraints gbc_panel_2_1_1 = new GridBagConstraints();
		gbc_panel_2_1_1.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_1.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_1.gridx = 0;
		gbc_panel_2_1_1.gridy = 1;
		panel_2_1_1.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_1, gbc_panel_2_1_1);
		GridBagLayout gbl_panel_2_1_1 = new GridBagLayout();
		gbl_panel_2_1_1.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_1.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_1.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_1.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_1.setLayout(gbl_panel_2_1_1);
		
		GridBagConstraints gbc_panel_12_1_1 = new GridBagConstraints();
		gbc_panel_12_1_1.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_1.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_1.gridx = 0;
		gbc_panel_12_1_1.gridy = 0;
		panel_12_1_1.setForeground(Color.ORANGE);
		panel_12_1_1.setBorder(null);
		panel_12_1_1.setBackground(Color.ORANGE);
		panel_2_1_1.add(panel_12_1_1, gbc_panel_12_1_1);
		GridBagLayout gbl_panel_12_1_1 = new GridBagLayout();
		gbl_panel_12_1_1.columnWidths = new int[]{0};
		gbl_panel_12_1_1.rowHeights = new int[]{0};
		gbl_panel_12_1_1.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_1.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_1.setLayout(gbl_panel_12_1_1);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_1 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_1.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_1.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_1.gridy = 0;
		lbl_ArtikelnAnzeigen_1_1.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_1.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_1.add(lbl_ArtikelnAnzeigen_1_1, gbc_lbl_ArtikelnAnzeigen_1_1);
		
		GridBagConstraints gbc_panel_2_1_2 = new GridBagConstraints();
		gbc_panel_2_1_2.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_2.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_2.gridx = 0;
		gbc_panel_2_1_2.gridy = 2;
		panel_2_1_2.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_2, gbc_panel_2_1_2);
		GridBagLayout gbl_panel_2_1_2 = new GridBagLayout();
		gbl_panel_2_1_2.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_2.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_2.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_2.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_2.setLayout(gbl_panel_2_1_2);
		
		GridBagConstraints gbc_panel_12_1_2 = new GridBagConstraints();
		gbc_panel_12_1_2.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_2.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_2.gridx = 0;
		gbc_panel_12_1_2.gridy = 0;
		panel_12_1_2.setForeground(Color.ORANGE);
		panel_12_1_2.setBorder(null);
		panel_12_1_2.setBackground(Color.ORANGE);
		panel_2_1_2.add(panel_12_1_2, gbc_panel_12_1_2);
		GridBagLayout gbl_panel_12_1_2 = new GridBagLayout();
		gbl_panel_12_1_2.columnWidths = new int[]{0};
		gbl_panel_12_1_2.rowHeights = new int[]{0};
		gbl_panel_12_1_2.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_2.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_2.setLayout(gbl_panel_12_1_2);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_2 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_2.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_2.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_2.gridy = 0;
		lbl_ArtikelnAnzeigen_1_2.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_2.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_2.add(lbl_ArtikelnAnzeigen_1_2, gbc_lbl_ArtikelnAnzeigen_1_2);
		
		GridBagConstraints gbc_panel_2_1_3 = new GridBagConstraints();
		gbc_panel_2_1_3.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_3.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_3.gridx = 0;
		gbc_panel_2_1_3.gridy = 3;
		panel_2_1_3.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_3, gbc_panel_2_1_3);
		GridBagLayout gbl_panel_2_1_3 = new GridBagLayout();
		gbl_panel_2_1_3.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_3.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_3.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_3.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_3.setLayout(gbl_panel_2_1_3);
		
		GridBagConstraints gbc_panel_12_1_3 = new GridBagConstraints();
		gbc_panel_12_1_3.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_3.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_3.gridx = 0;
		gbc_panel_12_1_3.gridy = 0;
		panel_12_1_3.setForeground(Color.ORANGE);
		panel_12_1_3.setBorder(null);
		panel_12_1_3.setBackground(Color.ORANGE);
		panel_2_1_3.add(panel_12_1_3, gbc_panel_12_1_3);
		GridBagLayout gbl_panel_12_1_3 = new GridBagLayout();
		gbl_panel_12_1_3.columnWidths = new int[]{0};
		gbl_panel_12_1_3.rowHeights = new int[]{0};
		gbl_panel_12_1_3.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_3.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_3.setLayout(gbl_panel_12_1_3);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_3 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_3.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_3.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_3.gridy = 0;
		lbl_ArtikelnAnzeigen_1_3.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_3.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_3.add(lbl_ArtikelnAnzeigen_1_3, gbc_lbl_ArtikelnAnzeigen_1_3);
		
		GridBagConstraints gbc_panel_2_1_4 = new GridBagConstraints();
		gbc_panel_2_1_4.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_4.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_4.gridx = 0;
		gbc_panel_2_1_4.gridy = 4;
		panel_2_1_4.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_4, gbc_panel_2_1_4);
		GridBagLayout gbl_panel_2_1_4 = new GridBagLayout();
		gbl_panel_2_1_4.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_4.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_4.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_4.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_4.setLayout(gbl_panel_2_1_4);
		
		GridBagConstraints gbc_panel_12_1_4 = new GridBagConstraints();
		gbc_panel_12_1_4.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_4.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_4.gridx = 0;
		gbc_panel_12_1_4.gridy = 0;
		panel_12_1_4.setForeground(Color.ORANGE);
		panel_12_1_4.setBorder(null);
		panel_12_1_4.setBackground(Color.ORANGE);
		panel_2_1_4.add(panel_12_1_4, gbc_panel_12_1_4);
		GridBagLayout gbl_panel_12_1_4 = new GridBagLayout();
		gbl_panel_12_1_4.columnWidths = new int[]{0};
		gbl_panel_12_1_4.rowHeights = new int[]{0};
		gbl_panel_12_1_4.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_4.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_4.setLayout(gbl_panel_12_1_4);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_4 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_4.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_4.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_4.gridy = 0;
		lbl_ArtikelnAnzeigen_1_4.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_4.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_4.add(lbl_ArtikelnAnzeigen_1_4, gbc_lbl_ArtikelnAnzeigen_1_4);
		
		GridBagConstraints gbc_panel_2_1_5 = new GridBagConstraints();
		gbc_panel_2_1_5.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_5.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_5.gridx = 0;
		gbc_panel_2_1_5.gridy = 5;
		panel_2_1_5.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_5, gbc_panel_2_1_5);
		GridBagLayout gbl_panel_2_1_5 = new GridBagLayout();
		gbl_panel_2_1_5.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_5.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_5.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_5.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_5.setLayout(gbl_panel_2_1_5);
		
		GridBagConstraints gbc_panel_12_1_5 = new GridBagConstraints();
		gbc_panel_12_1_5.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_5.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_5.gridx = 0;
		gbc_panel_12_1_5.gridy = 0;
		panel_12_1_5.setForeground(Color.ORANGE);
		panel_12_1_5.setBorder(null);
		panel_12_1_5.setBackground(Color.ORANGE);
		panel_2_1_5.add(panel_12_1_5, gbc_panel_12_1_5);
		GridBagLayout gbl_panel_12_1_5 = new GridBagLayout();
		gbl_panel_12_1_5.columnWidths = new int[]{0};
		gbl_panel_12_1_5.rowHeights = new int[]{0};
		gbl_panel_12_1_5.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_5.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_5.setLayout(gbl_panel_12_1_5);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_5 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_5.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_5.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_5.gridy = 0;
		lbl_ArtikelnAnzeigen_1_5.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_5.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_5.add(lbl_ArtikelnAnzeigen_1_5, gbc_lbl_ArtikelnAnzeigen_1_5);
		
		GridBagConstraints gbc_panel_2_1_6 = new GridBagConstraints();
		gbc_panel_2_1_6.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_6.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_6.gridx = 0;
		gbc_panel_2_1_6.gridy = 6;
		panel_2_1_6.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_6, gbc_panel_2_1_6);
		GridBagLayout gbl_panel_2_1_6 = new GridBagLayout();
		gbl_panel_2_1_6.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_6.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_6.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_6.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_6.setLayout(gbl_panel_2_1_6);
		
		GridBagConstraints gbc_panel_12_1_6 = new GridBagConstraints();
		gbc_panel_12_1_6.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_6.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_6.gridx = 0;
		gbc_panel_12_1_6.gridy = 0;
		panel_12_1_6.setForeground(Color.ORANGE);
		panel_12_1_6.setBorder(null);
		panel_12_1_6.setBackground(Color.ORANGE);
		panel_2_1_6.add(panel_12_1_6, gbc_panel_12_1_6);
		GridBagLayout gbl_panel_12_1_6 = new GridBagLayout();
		gbl_panel_12_1_6.columnWidths = new int[]{0};
		gbl_panel_12_1_6.rowHeights = new int[]{0};
		gbl_panel_12_1_6.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_6.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_6.setLayout(gbl_panel_12_1_6);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_6 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_6.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_6.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_6.gridy = 0;
		lbl_ArtikelnAnzeigen_1_6.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_6.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_6.add(lbl_ArtikelnAnzeigen_1_6, gbc_lbl_ArtikelnAnzeigen_1_6);
		
		GridBagConstraints gbc_panel_2_1_7 = new GridBagConstraints();
		gbc_panel_2_1_7.insets = new Insets(0, 0, 5, 0);
		gbc_panel_2_1_7.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_7.gridx = 0;
		gbc_panel_2_1_7.gridy = 7;
		panel_2_1_7.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_7, gbc_panel_2_1_7);
		GridBagLayout gbl_panel_2_1_7 = new GridBagLayout();
		gbl_panel_2_1_7.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_7.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_7.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_7.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_7.setLayout(gbl_panel_2_1_7);
		
		GridBagConstraints gbc_panel_12_1_7 = new GridBagConstraints();
		gbc_panel_12_1_7.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_7.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_7.gridx = 0;
		gbc_panel_12_1_7.gridy = 0;
		panel_12_1_7.setForeground(Color.ORANGE);
		panel_12_1_7.setBorder(null);
		panel_12_1_7.setBackground(Color.ORANGE);
		panel_2_1_7.add(panel_12_1_7, gbc_panel_12_1_7);
		GridBagLayout gbl_panel_12_1_7 = new GridBagLayout();
		gbl_panel_12_1_7.columnWidths = new int[]{0};
		gbl_panel_12_1_7.rowHeights = new int[]{0};
		gbl_panel_12_1_7.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_7.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_7.setLayout(gbl_panel_12_1_7);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_7 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_7.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_7.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_7.gridy = 0;
		lbl_ArtikelnAnzeigen_1_7.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_7.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_7.add(lbl_ArtikelnAnzeigen_1_7, gbc_lbl_ArtikelnAnzeigen_1_7);
		
		GridBagConstraints gbc_panel_2_1_8 = new GridBagConstraints();
		gbc_panel_2_1_8.fill = GridBagConstraints.BOTH;
		gbc_panel_2_1_8.gridx = 0;
		gbc_panel_2_1_8.gridy = 8;
		panel_2_1_8.setBackground(Color.DARK_GRAY);
		panel_1.add(panel_2_1_8, gbc_panel_2_1_8);
		GridBagLayout gbl_panel_2_1_8 = new GridBagLayout();
		gbl_panel_2_1_8.columnWidths = new int[]{26, 45, 0};
		gbl_panel_2_1_8.rowHeights = new int[]{13, 0};
		gbl_panel_2_1_8.columnWeights = new double[]{0.0, 1.0, Double.MIN_VALUE};
		gbl_panel_2_1_8.rowWeights = new double[]{1.0, Double.MIN_VALUE};
		panel_2_1_8.setLayout(gbl_panel_2_1_8);
		
		GridBagConstraints gbc_panel_12_1_8 = new GridBagConstraints();
		gbc_panel_12_1_8.fill = GridBagConstraints.BOTH;
		gbc_panel_12_1_8.insets = new Insets(0, 0, 0, 5);
		gbc_panel_12_1_8.gridx = 0;
		gbc_panel_12_1_8.gridy = 0;
		panel_12_1_8.setForeground(Color.ORANGE);
		panel_12_1_8.setBorder(null);
		panel_12_1_8.setBackground(Color.ORANGE);
		panel_2_1_8.add(panel_12_1_8, gbc_panel_12_1_8);
		GridBagLayout gbl_panel_12_1_8 = new GridBagLayout();
		gbl_panel_12_1_8.columnWidths = new int[]{0};
		gbl_panel_12_1_8.rowHeights = new int[]{0};
		gbl_panel_12_1_8.columnWeights = new double[]{Double.MIN_VALUE};
		gbl_panel_12_1_8.rowWeights = new double[]{Double.MIN_VALUE};
		panel_12_1_8.setLayout(gbl_panel_12_1_8);
		
		GridBagConstraints gbc_lbl_ArtikelnAnzeigen_1_8 = new GridBagConstraints();
		gbc_lbl_ArtikelnAnzeigen_1_8.fill = GridBagConstraints.BOTH;
		gbc_lbl_ArtikelnAnzeigen_1_8.gridx = 1;
		gbc_lbl_ArtikelnAnzeigen_1_8.gridy = 0;
		lbl_ArtikelnAnzeigen_1_8.setForeground(Color.WHITE);
		lbl_ArtikelnAnzeigen_1_8.setFont(new Font("Tahoma", Font.PLAIN, 16));
		panel_2_1_8.add(lbl_ArtikelnAnzeigen_1_8, gbc_lbl_ArtikelnAnzeigen_1_8);
	}

}
